
<div id="productinfo">
    <div class="viewerImage">
            <?php echo $this->getFoto($this->product['id'],2); ?>
    </div>
    <div class="viewerInfo">
            <h2 class="title-product">
                <span>
                    <?php echo $this->escape(($this->product['titel'])); ?>
                </span>
            </h2>

            <h2 class="teaser-product">
                <span>
                    <?php echo $this->escape(($this->product['teaser'])); ?>
                </span>
            </h2>

            <div class="prod-desc">
                    <?php echo $this->escape(($this->product['inhoud'])); ?>

            </div>

            <div class="prod-cat">
                <?php
                    if (!empty($this->categorie)) {
                        foreach($this->categorie as $c) {
                            echo "<p>".$this->escape($c['label'])."</p>";
                        }
                    }
                ?>
            </div>
            <?php echo $this->ToonProductstatus($this->product['status']); ?>

            

            <div class="prod-price">
                <?php echo $this->ShowCurrency($this->product['eenheidsprijs']); ?>
            </div>
        
            <form action="" method="post" enctype="multipart/form-data">
            <div class="add_to_cart_button">
                <a href="#"><div class="add_to_cart_image_button"><?php echo $this->translate("lblindewinkelwagen"); ?></div></a>
            </div>
            <div class="qty-price">
                <label><?php echo $this->translate("lblAantal"); ?></label>
                <?php
                $elemAttribs = array('class' => 'onlyDecimals', 'name' => 'Aantal' , 'style' => 'width:40px; font-size:22px;');
               
                echo $this->formHidden('id',$this->product['id']); 
                ?>
            </div>
            </form>
        
            <div class="prod-foto">
            <?php
            if (!empty($this->fotos)) {
                foreach($this->fotos as $f) {
            ?>
                <?php $source="/".$this->escape($f['filePath']).$this->escape($f['fileName']); ?>
                <a class="fancybox" href="<?php echo $source; ?>" data-fancybox-group="gallery" title="<?php echo $this->escape(($this->product['titel'])); ?>">

                <img class="productimage-3" alt="" src="<?php echo $source; ?>">
                
                </a>
                <?php
               }
            }
            ?>
            </div>
        </div>
</div>

<div class="divLoading"></div>
<?php echo $this->render('/index/_jsCustom_productinfo.phtml'); ?>

        <!-- Add mousewheel plugin (this is optional) -->
	<script type="text/javascript" src="/base/js/fancybox/helpers/jquery.mousewheel-3.0.6.pack.js"></script>

	<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="/base/js/fancybox/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="/base/js/fancybox/jquery.fancybox.css?v=2.1.5" media="screen" />

	<!-- Add Button helper (this is optional) -->
	<link rel="stylesheet" type="text/css" href="/base/js/fancybox/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
	<script type="text/javascript" src="/base/js/fancybox/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

	<!-- Add Thumbnail helper (this is optional) -->
	<link rel="stylesheet" type="text/css" href="/base/js/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
	<script type="text/javascript" src="/base/js/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

	<!-- Add Media helper (this is optional) -->
	<script type="text/javascript" src="/base/js/fancybox/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

