<?php
// ---------------------------------
// JAVASCRIPT
// --------------------------------- 
$this->jQuery()->onLoadCaptureStart(); ?>

        // Autocomplete foto
        $[ "ui" ][ "autocomplete" ].prototype["_renderItem"] = function( ul, item) {
            return $( "<li></li>" )
            .data( "item.autocomplete", item )
            .append( $( "<a></a>" ).html( item.label ) )
            .appendTo( ul );
        };

        $("#Autocomplete").focus(function(event) {
            if ($(this).val().length == 0) {
                $(this).autocomplete("search");
            }
      });

<?php 
$this->jQuery()->onLoadCaptureEnd();
?>