<?php 
$ii=0;
if (!empty($this->result)){
	$img="<img src='".$this->baseUrl()."/images/success.gif"."'>";
?>

<?php if (!empty($this->form)) {
	       echo $this->form;
		}
?>
<div class="hoofding"><?php echo $this->translate('Ploegen');?></div>
<br/>
<table  class="hic" style="width:40%;">
	<thead>
	<tr>
		<th>
			<?php echo $this->translate('Nr'); ?>
		</th>
		<th>
			<?php echo $this->translate('Naam'); ?>
		</th>                	
	</tr>
	</thead>
	<tbody>
        <?php foreach ($this->result as $r) { ?>
        <?php $ii++;?>
	<tr>
		<td>
                    <?php echo $ii; ?>    
		</td>
		<td style="text-align:right;">
			<a href="<?php echo $this->baseUrl();?>/admin/ploegen/id/<?php echo $r['id']; ?>"><?php echo ($r['status'])?'<span style="text-decoration:line-through;">'.$r['naam'].'</span>':$r['naam']; ?> </a>   
		</td>
                <td>
			<img  src="/images/vlaggen/<?php echo $r['naam'];?>.png"></img>   
		</td>
	</tr>
        <?php } ?>
	</tbody>	
</table>
<?php 
}
?>
<div id="messages"></div>
<div id="divLoading"></div>
<?php echo $this->render('/admin/_jsCustom_ploeg.phtml'); ?>