<?php if (!empty($this->id)) {?>

<?php //------------------------------------------------------------------------?>
<?php if ($this->id<=48) {?>
<form name="wkprono" id="wkprono" method="post" action="">
	<table>
		<tr>
		<td>
		<div class='hoofding'>Uitslag wedstrijd</div>
		<div class='groep'>
			<table width='100%' cellspacing='1' cellpadding='1' border='0'>
			<tr>
			<td><?php echo $this->wedstrijd['thuis'];?></td>
                        <td >
			<img  src='<?php echo ($this->baseUrl()."/images/vlaggen/".trim($this->wedstrijd['thuis']) .".png");?>'/>
			</td>
			<td>-</td>
			<td>
			<img src='<?php echo $this->baseUrl()."/images/vlaggen/".trim($this->wedstrijd['uit']) .".png";?>'>
                        </td>
                        <td>
                        <?php echo $this->wedstrijd['uit'];?>
			</td>	
			<td>
			<input type='text' class='onlyDecimals' size='1' maxlength='2' name='uitslag1' id='uitslag1'>
			</td>
			<td>-</td>
			<td>
			<input type='text' class='onlyDecimals' size='1' maxlength='2' name='uitslag2' id='uitslag2'>
			</td>
			</tr>
			<tr>
			<td>			
			</td>
			</tr>
			
			<tr>
			<td colspan='6' align='center'>
				<input type='hidden' name='id' id='id' value="<?php echo $this->id;?>">
				<input type="submit" value="<?php echo $this->translate('Opslaan'); ?>" name="btn_save" id="btn_save">
			</td>
			</tr>
			</table>
		</div>
		</div>	
		</td>	
		</tr>
	</table>
</form>
<?php } ?>

<?php //------------------------------------------------------------------------?>
<?php if ($this->id>48 and $this->id<66) {?>
<form name="wkprono" id="wkprono" method="post" action="">
	<table>
		<tr>
		<td>
		<div class='hoofding'>Wedstrijd <?php echo $this->wedstrijd['id'];?></div>
		<div class='groep'>
			<table width='100%' cellspacing='1' cellpadding='1' border='0'>
			<tr>
			<td><?php //echo $this->wedstrijd['thuis'];?>
			<?php echo $this->formSelect('thuis',null,array(),$this->ploegen ); ?>
			</td>
			<td>-</td>
			<td>			
			<?php //echo $this->wedstrijd['uit'];?>
			<?php echo $this->formSelect('uit',null,array(),$this->ploegen ); ?>
			</td>	
			<td>
			<input type='text' class='onlyDecimals' size='1' maxlength='2' name='uitslag1' id='uitslag1'>
			</td>
			<td>-</td>
			<td>
			<input type='text' class='onlyDecimals' size='1' maxlength='2' name='uitslag2' id='uitslag2'>
			</td>
			</tr>
			<tr>
			<td>			
			</td>
			</tr>
			
			<tr>
			<td colspan='6' align='center'>
				<input type='hidden' name='id' id='id' value="<?php echo $this->id;?>">
				<input type="submit" value="<?php echo $this->translate('Opslaan'); ?>" name="btn_save2" id="btn_save2">
			</td>
			</tr>
			</table>
		</div>
		</div>	
		</td>	
		</tr>
	</table>
</form>
<?php } ?>

<?php } ?>
<table width="870" cellspacing="5" cellpadding="5" border="0">
	<tbody>		
		<tr>
		<td width="50%" valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,1,0); ?>
		</td>
		<td width="50%" valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,2,0); ?>
		</td>
		</tr>
		<tr>
		<td width="50%" valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,3,0); ?>
		</td>
		<td width="50%" valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,4,0); ?>
		</td>
		</tr>
		
		<tr>
		<td width="50%" valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,5,0); ?>
		</td>
		<td width="50%" valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,6,0); ?>
		</td>
		</tr>
		
		
		<tr>
		<td width="50%" valign="top" >
			<?php echo $this->GetFinaleWedstrijden3($this->wedstrijden,9,0); ?>
		</td>
		<td width="50%" valign="top">
			<?php echo $this->GetFinaleWedstrijden3($this->wedstrijden,10,0); ?>
		</td>
		</tr>
		
		<tr>
		<td width="50%" valign="top" >
			<?php echo $this->GetFinaleWedstrijden3($this->wedstrijden,11,0); ?>
		</td>
		<td width="50%" valign="top">
			<?php echo $this->GetFinaleWedstrijden3($this->wedstrijden,12,0); ?>
		</td>
		</tr>
		
		
	</tbody>
</table>

<div id="messages"></div>
<div id="divLoading"></div>
<?php echo $this->render('/admin/_jsCustom_wedstrijd.phtml'); ?>

